title: "CLARISSA: A Conversational User Interface for Democratizing Reservoir Simulation"
conference: "SPE Europe Energy Conference 2026"
category: "05.6 ML/AI in Subsurface Operations"

authors:
  - name: Douglas Perschke
    affiliation: Stone Ridge Technology, USA
    role: Domain Expertise (Reservoir Engineering)
    
  - name: Michal Matejka
    affiliation: Independent Consultant, Houston, USA
    role: Technical Review
    
  - name: Wolfram Laube
    affiliation: Independent Researcher, Austria
    role: Technical Architecture

version: "1.1.1"
last_updated: "2026-01-14"

# Document structure
documents:
  full_paper:
    source: "full-paper.md"
    description: "Complete technical paper with all sections and diagrams"
    outputs:
      - "full-paper.html"
      - "full-paper.pdf"
      
  submission_form:
    source: "submission-form.md"
    description: "SPE abstract submission form (4 sections, ~500 words)"
    outputs:
      - "submission-form.html"
      - "submission-form.pdf"

# Diagram sources (rendered by CI)
diagrams:
  source_dir: "../diagrams"
  output_formats: ["svg", "png"]
  files:
    - architecture.mmd
    - phases.mmd
    - comparison.mmd
    - rigor.mmd
    - conversation.mmd
    - techstack.mmd

# CI Pipeline triggers
triggers:
  llm_merge: "sources/**/*"
  artifact_generation: 
    - "canonical/**/*"
    - "diagrams/*.mmd"

last_build: "2026-01-15T10:24:08.521935"
