#!/usr/bin/env python3
"""Generate a simple HTML gallery for rendered architecture diagrams.

Inputs:
  - docs/architecture/rendered/*.svg (preferred) or *.png

Outputs:
  - docs/architecture/rendered/index.html
  - docs/architecture/rendered/index.md
"""
from __future__ import annotations
from pathlib import Path
import html

def main() -> int:
    out_dir = Path("docs/architecture/rendered")
    out_dir.mkdir(parents=True, exist_ok=True)

    svgs = sorted(out_dir.glob("*.svg"))
    pngs = sorted(out_dir.glob("*.png"))
    imgs = svgs or pngs

    md_lines = ["# Architecture diagram gallery", "", "Artifacts generated by CI."]
    md_lines.append("")
    if not imgs:
        md_lines.append("_No rendered diagrams found. See `docs/architecture/diagrams/*.mmd`._")
    else:
        md_lines.append("## Rendered diagrams")
        md_lines.append("")
        for p in imgs:
            md_lines.append(f"- `{p.name}`")
    (out_dir / "index.md").write_text("\n".join(md_lines) + "\n", encoding="utf-8")

    html_lines = [
        "<!doctype html>",
        "<html><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        "<title>ORSA Architecture Diagrams</title>",
        "<style>body{font-family:system-ui,Segoe UI,Arial,sans-serif;max-width:1100px;margin:24px auto;padding:0 16px;line-height:1.35}"
        "h1{margin:0 0 12px} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}"
        ".card{border:1px solid #ddd;border-radius:14px;padding:12px;box-shadow:0 2px 10px rgba(0,0,0,.05)}"
        ".card img{width:100%;height:auto;border-radius:10px} .meta{font-size:14px;color:#444;margin-top:8px}</style>",
        "</head><body>",
        "<h1>ORSA Architecture Diagrams</h1>",
        "<p>Rendered artifacts (SVG/PNG). Canonical sources live in <code>docs/architecture/diagrams/*.mmd</code>.</p>",
    ]

    if not imgs:
        html_lines.append("<p><em>No rendered diagrams found.</em></p>")
    else:
        html_lines.append("<div class='grid'>")
        for p in imgs:
            html_lines.append("<div class='card'>")
            html_lines.append(f"<img src='{html.escape(p.name)}' alt='{html.escape(p.name)}'/>")
            html_lines.append(f"<div class='meta'>{html.escape(p.name)}</div>")
            html_lines.append("</div>")
        html_lines.append("</div>")

    html_lines.append("</body></html>")
    (out_dir / "index.html").write_text("\n".join(html_lines), encoding="utf-8")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
